### ISSUE TITLE
models: update catch streams

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#41] opened 2021-05-15 00:19 UTC
Run the 2019 model with updated catch streams b/c it is pretty easy to add the northern CA back into the rest of CA to mimic the previous assessment. This will be the start of our bridging analysis. The catch streams will be available by Monday (2021-05-17) for this model run.

**Comment by iantaylor-NOAA** [comment] 2021-05-18 00:16
Thanks @andi-stephens-NOAA for volunteering for this.
I will provide an example scripted workflow using r4ss functions.
@kellijohnson-NOAA will provide updated catch streams.

**Comment by iantaylor-NOAA** [comment] 2021-05-24 17:58
@andi-stephens-NOAA, I've refined the workflow for moving from one model to the next and documented it in the [README](/github.com/iantaylor-NOAA/Lingcod_2021#Modeling-workflow)

I also provided the template on these lines: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/lingcod_model_bridging_new_exe.R#L121-L149
for the process of changing the catch streams to the ones provided by @kellijohnson-NOAA linked above in https://github.com/iantaylor-NOAA/Lingcod_2021/issues/41#issuecomment-843280676.

Can you take a look and see if what I've written in those two places makes sense? If so, go ahead and put together this catch stream sensitivity for the 2019 model. If not, let me know and we can figure out how to improve things.

Initially this workflow will definitely be more work than just copying and pasting numbers from spreadsheets, but I have faith that it will both become second nature eventually and pay off in the long run in transparency, accuracy and reproducibility of our work.

**Comment by iantaylor-NOAA** [comment] 2021-05-24 18:02
Typo in previous commit for README link now fixed to https://github.com/iantaylor-NOAA/Lingcod_2021#Modeling-workflow. Posting again so folks don't get frustrated by bad link in email notification.

**Comment by andi-stephens-NOAA** [comment] 2021-06-05 00:13
Replaced the 2019 commercial catches in N and S models.

**Closed by andi-stephens-NOAA** 2021-06-05 00:13 UTC
Labels: 2021-05-21

**Comment by iantaylor-NOAA** [comment] 2021-06-06 22:16
Thanks @andi-stephens-NOAA for completing these runs. 

The differences in the south model mostly occur during the time period with the greatest changes in catch, but the recent, data-rich period has very similar results. The south model with new catch is also higher at the very end of the time series because the original model a -0.86 value for the 2016 recdev (`mod.2019.s.002.002$parameters["Late_RecrDev_2016", "Value"]`) while the new run treated that year as fixed at 0. I'm not sure what the reasons for that difference are, but I don't think it's worth dwelling on now. The north models are very similar as expected.

The commands to make these comparison figures are at the bottom of an existing script: https://github.com/iantaylor-NOAA/Lingcod_2021/blob/main/models/lingcod_model_bridging_newfleets.R#L160-L180. 
@andi-stephens-NOAA, if you have a script containing the commands to add these catch streams, go ahead and commit it to the repo and one of us can add those comparison commands to it.

Maybe it would be better to have a separate script for plotting the comparisons in the bridging or just intersperse plotting commands with the commands related to modifying the model files. We can always create one later if we wish.

![compare_2019 s 002 002_2019 s 003 001](https://user-images.githubusercontent.com/4992918/120939879-089d7980-c6cf-11eb-810e-cae6687e08b6.png)

![compare_2019 n 002 001_2019 n 003 001](https://user-images.githubusercontent.com/4992918/120941843-e65d2900-c6d9-11eb-8240-fc97298e7b88.png)

**Comment by andi-stephens-NOAA** [comment] 2021-06-07 16:32
I added the catch-streams by hand, using some of the commands in the
existing scripts, but I can see if I can dump history to a file and edit it
to make a script if you think that would be helpful.

I was too wiped out on Friday to look at model results-- thanks for your
notes on the differences.

Cheers,

--Andi
