### ISSUE TITLE
California composition data

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [iantaylor-NOAA/Lingcod_2021#47] opened 2021-05-25 17:01 UTC
John B. provided many files. Here is an attempt to organize information provided in files and emails ...

*    Provided and should be used in base model: 
     * CRFS - SD501...; 2001-2020; Remove samples from MEXICO using "AGENCY_WATER_AREA_NAME"
     * MRFSS
*    Provided and NOT being used in base model but could be a sensitivity
     *    **DISCARD** 
          *    length composition data from discarded fish measured on CPFVs from 1980-2019 that was not included in last assessment; JB thinks that it could be an indicator of recruitment strength; data are from recfin with IS_RETAINED == RELEASED
          *    Type3d data from discards measured onboard CPFVs collected in 2003 prior to the transition to CRFS. This data is already available in the SD501...: 2001-2020 data file. 
*    Not provided but should be
     *    Get from Jason Cope
          *    CPFV 1980-1990 length samples: data are analogous to MRFSS and CRFS; n = 13739
          *    CPFV 1950-1970 length samples; limited spatial distribution; Avila/Morrow Bay to Trinidad, but mostly Avila to Santa Cruz
     *    ROV observations north of Point Conception by depth
*    Not provided, but will be noted for future assessments
     *    Ages from California Cooperative Groundfish Survey (CCGS) that were processed but not aged; Recreational carcasses from Monterey with (n = 163) and without sex information from 2017-2019; lengths are of carcasses without conversions to total lengths
     *    Hook-And-Line caught commercial ages that were processed but not aged; purchased from the fishery and collected between April - June 2019 (n = 49)

Given the above, it looks like we have the following tasks:
- [ ] get ROV data (KFJ)
- [x] get early lengths from Jason Cope (BL)
  - [x] work them up (BL)
- [x] find out if any of the CCGS ages were aged (KFJ)
- [x] get draft text for the assessment from John B. regarding processed but unaged fins from CCGS

**Comment by brianlangseth-NOAA** [comment] 2021-05-28 21:44
Thanks to Jason Cope for providing the early length data. I will put a link to the drive folder that jason provided within our data-raw drive folder. I believe access will be limited some may need to request access to that folder. @kellijohnson-NOAA There are a lot of data in the folder, JohnB mentioned "I highlighted the data sources that might be of interest for lengths in the 1970s and to supplement the 1980s" could you provide that here? 

What is our timeline for working these data up?

**Comment by brianlangseth-NOAA** [comment] 2021-06-02 20:39
Here are my decisions based on my sluething of the historical datasets provided for CA. Although these are separated into south, central, and north datasets, pretty much all of the areas are south of 40'10. Thus my recommendation is that these only be used for the southern model. Unless I hear from others with strong opinions otherwise, I will start to work these up. 

Southern California:
865 lengths, 1985-1988, Onboard Crooke and Ally (86-88), recreational fishery 
832 lengths, 1975-1978, Onboard Crooke and Ally CPFV, recreational fishery

Central California:
8722 lengths, 1987-1998, DebWV CPFV Onboard data, recreational fishery

Northern California:
722 lengths, 1977-1986, Dockside CCRS_LF, recreational fishery (party boat)
4818 lengths, 1959-1972, FPB_LF, recreational fishery (party boat)
4307 lengths, 1959-1972, Skiff_LF, recreational fishery (skiffs)

**Comment by iantaylor-NOAA** [comment] 2021-06-02 21:16
I'm fine with zero lengths for the CA rec fleet north of 40-10 (and therefore mirroring selectivity to the OR rec fleet).

Ideally the final product would be a single rec length composition vector for each year, but I'm not sure how best to aggregate across these groups or determine the input sample sizes.

**Comment by brianlangseth-NOAA** [comment] 2021-06-02 21:35
@iantaylor-NOAA  Just to be clear, this is only for the historical data. MRFS and RecFIN data have loads of lengths, so the northern model will have plenty to use. I plan to combine all of these together so there will only be one value for each year.

**Comment by melissamonk-NOAA** [comment] 2021-06-02 23:33
@brianlangseth-NOAA  I wouldn't combine Deb's lengths with other since you'll have an index for those.

**Comment by iantaylor-NOAA** [comment] 2021-06-02 23:55
Good point @melissamonk-NOAA.

However, at this point we're following the assumption used in previous Lingcod assessments that all CA Rec catch is pooled as a single fleet rather than separating party/charter boats from private boats.

We could still represent the index and associated lengths as a separate fleet from the rest of the CA rec data but if we estimate a separate selectivity for that fleet, then we're saying that the other CA length comps are more representative of the catch than these. And if we mirror the selectivity, I think the result will be equivalent to aggregating the length comps in the first place. I suppose keeping them separate, even with mirrored selectivity, allows separate diagnostics for the fit to different sources, but I'm not sure we'll have time to dig into that level of detail given the timeline we're on.

**Comment by melissamonk-NOAA** [comment] 2021-06-03 00:10
@iantaylor-NOAA I get that and will leave it up to you all!

**Comment by brianlangseth-NOAA** [comment] 2021-06-03 23:46
Worked up historical CPFV datasets with commit 46e0dce23caa90b1adca9d291b19aed010398b72

All but the Deb Wilson-Vandenberg dataset (DebWV) are combined with the recreational fleet comps and have released fish removed (as we have been doing for the rec fleets). 

The Deb Wilson-Vandenberg dataset is treated as a separate fleet (new fleet added with commit bf64245c2b645ecb8766fefd7aeed91477e78120) and because the index includes landed and discarded, the comps include released and retained fish.  Only used fishing locations south of 40.10 for this dataset.

**Comment by melissamonk-NOAA** [comment] 2021-06-04 15:33
@kellijohnson-NOAA  and @brianlangseth-NOAA, It sounds like you're now separating the discard and retained rec comps.  If so, the indices can reflect that, I just need to know :)

**Comment by brianlangseth-NOAA** [comment] 2021-06-04 21:38
After discussing with @melissamonk-NOAA and @iantaylor-NOAA  , the debWV index and comps should reflect discard and retained comps (which Melissa already provided, though please correct me if Im wrong). @kellijohnson-NOAA, Melissa will send you an updated index for CA rec, which previously included both discard and retained fish. The new index will contain just retained fish. 

Regarding CalPoly data: these are included in the rec index, and Melissa will provide us with the length data. We decided these will not go into the model as comps, consistent with the past assessment, but @brianlangseth-NOAA will confirm these lengths are not noticeably different than existing rec data.

**Comment by kellijohnson-NOAA** [comment] 2021-06-04 23:35
Thanks for the figure @brianlangseth-NOAA! This is great stuff. How many unsexed NA are in the lower left? Hopefully not many and we just toss those right?

**Comment by brianlangseth-NOAA** [comment] 2021-06-08 15:17
MRFSS doesn't have a distinction between retained and released within the dataset, so that is the full dataset. As there is no way to know how many were released (if at all - I think MRFSS samples after fishing is done), we should assume they are all retained. Thus, a more accurate figure would be to assign MRFSS as retained, and then plot the MRFSS data in with the "Retained U" subpanel. I can update if we use for the report or presentation

**Comment by aliwhitman** [comment] 2021-06-08 15:59
I can confirm that MRFSS is retained fish only.

**Closed** 2021-06-30 18:57 UTC
Labels: topic: data
